### PR TITLE
Update to 0.21.2

### PR DESCRIPTION
**Pull request by ProfLeao**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin please rerender

**Comment by synapticarbors** [comment]
You deleted `recipe/meta.yaml` and renamed it `river/meta.yaml`, which is not correct. If you want to modify the recipe, please change it in `recipe/meta.yaml`.

**Comment by synapticarbors** [comment]
Additionally you removed the current maintainers, which I will not approve.

**Comment by ProfLeao** [comment]
Hi, @synapticarbors. Thank you very much for your comments. I'm just learning how to do this. I'll do as you say.

**Comment by synapticarbors** [comment]
I actually started a new PR in #28. I'm hoping I can get it working there. Also I appreciated the reminder that this feedstock has gotten out of date and the need to work on it.

**Comment by ProfLeao** [comment]
> I actually started a new PR in #28. I'm hoping I can get it working there. Also I appreciated the reminder that this feedstock has gotten out of date and the need to work on it.

Okay. I'll close this one and follow your progress.

**Comment by ProfLeao** [comment]
Closing a transferring to https://github.com/conda-forge/river-feedstock/pull/28

**Comment by ProfLeao** [comment]
Closing a transferring to https://github.com/conda-forge/river-feedstock/pull/28

**Pull request closed without merging**
